// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ElasticSearchTypeProvider")>]
[<assembly: AssemblyProductAttribute("ElasticSearchTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("An F# type provider for ElasticSearch")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ElasticSearchTypeProvider"
    let [<Literal>] AssemblyProduct = "ElasticSearchTypeProvider"
    let [<Literal>] AssemblyDescription = "An F# type provider for ElasticSearch"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
